apiVersion: ocular.crashoverride.run/v1beta1
kind: Downloader
metadata:
  name: gcs
spec:
  container:
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      valueFrom:
        secretKeyRef:
          key: downloader-gcs-credentials
          name: downloaders-secrets
          optional: true
    image: downloaders
    name: gcs
    resources: {}
status: {}
